# Generated by Django 5.2 on 2025-04-29 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterreadingsession',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='meterreadingsession',
            name='longitude',
        ),
    ]
