# Generated by Django 5.2 on 2025-05-05 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0004_alter_meterreadingsession_reader'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='meterreadingsession',
            constraint=models.UniqueConstraint(fields=('reader', 'date'), name='unique_reader_date'),
        ),
    ]
